name: 📝 Manuscript
description: File a new manuscript
title: "[Manuscript] <title>"
labels: ["Bug", "Needs Triage"]
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this manuscript report!

        Kindly review the file <a href="www.google.com">xxx</a> for guidance on completing this form.

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      #description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true

  - type: checkboxes
    attributes:
      label: Have you checked how the manuscripts are reported?
      #description: Please have a look at the manuscript .xls file.
      options:
      - label: I have had a look the existing manuscripts.
        required: true

  - type: input
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: input
    attributes:
      label: Link to manuscript
      description: Provide a link to the original manuscript.
      placeholder: ex. http://xxxx.com/manuscript01
    validations:
      required: false

  - type: textarea
    attributes:
      label: Brief description
      description: A concise description of the manuscript
    validations:
      required: false

  #- type: input
  #  attributes:
  #    label: Year
  #    placeholder: ex. 2022
  #  validations:
  #    required: false

  #- type: input
  #  attributes:
  #    label: Authors
  #    placeholder: ex. Hernandez et al
  #  validations:
  #    required: false

  - type: input
    attributes:
      label: Tags
      description: Provide a few tags that describe the manuscript.
      placeholder: ex. Sepsis | FNN | CNN | GRU | SOFA
    validations:
      required: false

  - type: input
    attributes:
      label: Score
      description: The mark you give to the manuscript (0-10).
      placeholder: ex. 6.5
    validations:
      required: false

  - type: textarea
    attributes:
      label: Clinical setting
      description: |
        A concise description of the clinical setting and inclusion criteria.
          - **Aim**: Prediction
          - **Condition(s)**: BSI
          - **Ward(s)**: ICU
          - **Dataset(s)**: MIMIC | eICU
          - **Inclusion criteria**: Age>18, inpatient, underwent blood culture
      value: |
          - Aim:
          - Condition(s):
          - Ward(s):
          - Dataset(s):
          - Inclusion criteria:
      render: markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Data
      description: |
        A concise description of the datasets used.
          - **Observation type**: episodes
          - **Total**: 6557
          - **Positive**: 877
          - **Prevalence**: 13.38%
      value: |
          - Observation type:
          - Total:
          - Positive:
          - Prevalence:
      render: markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Brief description of the data
      description: |
        A concise description of the data.

        Example:
        period: 2011-2015

        3969 patients admitted
        4582 blood culture episodes

        total, neg, none, pos
        total: 6557, 4319, 1361, 877
        train (70%): 4582, 3039, 940, 603
        val (20%): 1320, 852, 283, 185
        test (10%): 655, 428, 138, 89
        (see Table 1)

        none  = culture not drawn at all
    validations:
      required: false

  - type: textarea
    attributes:
      label: Brief description of the clinical variables
      description: |
        Example:
          Age + (26 features x 48 timesteps) (t=1h) (appendix B)
          Demographics (1): Age
          Vital Signs (4): BT, DBP, HR, RR, HR_STD, RR_STD, CORR_HR_RR
          Laboratory (22): BUN, ALB, PLT, Chloride, Creatinine, Phosphorus, ALP, SO2, PCO2, SPO2, Glucose,...
          Other (0):

  - type: textarea
    attributes:
      label: Brief description of the pre-processing
      description: |
        A concise description of pre-processing (example)
        Outlier Removal: None
        Class Imbalance: RANDU, RANDO, SMOTE
        Missing inputation (M):
          median, mean, forward fill, backward fill, multiple imputation, ...
        Feature Engineering (FE):
          - PaO2/FiO2 (FE_CRAFTED)
          - min, max, mean (FE_STATS)
          - time differences (FE_DELTA)
          - missing mask (FE_MASK)
          ...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Performance
      description: |
        A concise report of model performance.


        LB LA FxT Model AUCROC AUCPR SENS SPEC ...
        5h 3h 10x5 SVM 0.9 0.2 0.8 0.4
        5h 3h 10x5 GRU X.X X.X X.X X.X
        3h 3h 10x3 XGB X.X X.X X.X X.X
        3h 3h 10x3 SOFA X.X X.X X.X X.x

        LB: Look-back window; LA: Look ahead window; FxT: Feature x Timesteps; AUCROC: Area under the ROC;
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Materials
      description: What material is available to use.
      options:
      - label: Is the data publicly available?
        required: true
      - label: Is the code publicly available?
        required: true


  - type: textarea
    attributes:
      label: Feature ranking
      description: A concise description of the reported feature ranking (if any)
    validations:
      required: false

  - type: textarea
    attributes:
      label: Target definition
      description: A concise description of target definition (e.g. sepsis definition)
    validations:
      required: false

  - type: textarea
    attributes:
      label: Comments
      description: Provide any comments that might be useful.
      placeholder: ex. Interesting missing inputation and detailed performance reported in supplementary material
    validations:
      required: false

  - type: textarea
    attributes:
      label: Concerns
      description: Provide any concerns that you might have regarding the manuscript.
      placeholder: ex. Excessive feature engineering might have led to overfitting
    validations:
      required: false

  - type: textarea
    attributes:
      label: List of acronyms
      description: Please include any acronym used above.
      placeholder: ex. CNN Convolutional Neural Network
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  #- type: dropdown
  #  attributes:
  #    label: What browsers are you seeing the problem on?
  #    multiple: true
  #    options:
  #      - Firefox
  #      - Chrome
  #      - Safari
  #      - Microsoft Edge