#name: ⚕️Clinical Scoring System
name: Clinical Scoring System
description: File a new clinical scoring system entry
title: "[Manuscript] <title>"
labels: ["submission", "score"]
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this clinical scoring system report!

        Kindly review the file <a href="www.google.com">xxx</a> for guidance on completing this form.

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
      - label: I have searched the existing issues
        required: true

  - type: checkboxes
    attributes:
      label: Have you checked how the clinical scoring systems are reported?
      options:
      - label: I have reviewed the existing clinical scoring systems.
        required: true

  - type: input
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: input
    attributes:
      label: Link to manuscript
      description: Provide a link to the original manuscript.
      placeholder: ex. http://xxxx.com/manuscript01
    validations:
      required: false

  - type: textarea
    attributes:
      label: Brief description
      description: A concise description of the clinical scoring system
    validations:
      required: false

  - type: input
    attributes:
      label: Year
      placeholder: ex. 2022
    validations:
      required: false

  - type: input
    attributes:
      label: Tags
      description: Provide a few tags that describe the manuscript.
      placeholder: ex. Sepsis | ...
    validations:
      required: false

  - type: input
    attributes:
      label: Score
      description: The mark you give to the manuscript (0-10).
      placeholder: ex. 6.5
    validations:
      required: false

  - type: input
    attributes:
      label: Aim
      description: The aim of the score.
      placeholder: ex. Alertness | Truma | Severity | Mortality | ...
    validations:
      required: false

  - type: input
    attributes:
      label: Acronym
      description: The acronym of the score.
      placeholder: ex. GCS
    validations:
      required: false

  - type: input
    attributes:
      label: Range
      description: The possible range of the score.
      placeholder: ex. 0-25
    validations:
      required: false

  - type: textarea
    attributes:
      label: Clinical variables
      description: The clinical variables used to compute the score.
      placeholder: ex. Age, BT, MAP, PH_BG, HR, RR, HCT, WNC, GCS, FiO2
    validations:
      required: false

  - type: textarea
    attributes:
      label: Definition
      description: |
        The definition of the clinical score.

        If it is too complex just refer to the manuscript.
      placeholder: ex. see look-up table 3
    validations:
      required: false


  - type: textarea
    attributes:
      label: Clinical setting
      description: |
        A concise description of the clinical setting and inclusion criteria.
          - **Design**: Panel of Experts | Logisic Regression | ...
          - **Countries(s)**: USA and Spain
          - **Ward(s)**: 8 ICUs
          - **Patients**: 5815
          - **Inclusion criteria**: Age>18, inpatient, underwent blood culture
      value: |
          Design:
          Countries(s):
          Ward(s):
          Patients(s):
          Inclusion criteria:
      render: markdown
    validations:
      required: false


  - type: checkboxes
    attributes:
      label: Mortality
      description: Other relevant information.
      options:
      - label: Performs mortality prediction?
        required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Online calculators (e.g., medcalc link)
        Anything that will give us more context?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  #- type: dropdown
  #  attributes:
  #    label: What browsers are you seeing the problem on?
  #    multiple: true
  #    options:
  #      - Firefox
  #      - Chrome
  #      - Safari
  #      - Microsoft Edge