name: Manuscript
description: File a new manuscript
title: "[Manuscript] <title>"
labels: ["Bug", "Needs Triage"]
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true

  - type: checkboxes
    attributes:
      label: Have you checked how the manuscripts are reported?
      description: Please have a look at the manuscript .xls file.
      options:
      - label: I have had a look the existing manuscripts.
        required: true

  - type: input
    attributes:
      label: Link to manuscript
      description: Provide a link to the original manuscript.
      placeholder: ex. http://xxxx.com/manuscript01
    validations:
      required: false

  - type: textarea
    attributes:
      label: Brief description
      description: A concise description of the manuscript
    validations:
      required: false

  #- type: input
  #  attributes:
  #    label: Year
  #    placeholder: ex. 2022
  #  validations:
  #    required: false

  #- type: input
  #  attributes:
  #    label: Authors
  #    placeholder: ex. Hernandez et al
  #  validations:
  #    required: false

  - type: input
    attributes:
      label: Tags
      description: Provide a few tags that describe the manuscript.
      placeholder: ex. Sepsis | FNN | CNN | GRU | SOFA
    validations:
      required: false

  - type: input
    attributes:
      label: Score
      description: The mark you give to the manuscript (0-10).
      placeholder: ex. 6.5
    validations:
      required: false

  - type: textarea
    attributes:
      label: Criteria
      description: |
        A concise description of the clinical setting and inclusion criteria
          - **Aim**: Prediction
          - **Condition(s)**: BSI
          - **Ward(s)**: ICU
          - **Dataset(s)**: MIMIC | eICU
          - **Inclusion criteria**: Age>18, inpatient, underwent blood culture
      value: |
          - Aim:
          - Condition(s):
          - Ward(s):
          - Dataset(s):
          - Inclusion criteria:
      render: markdown
    validations:
      required: false

  - type: input
    attributes:
      label: Data
      description: |
        A concise description of the datasets used.
          - **Observation type**: episodes
          - **Total**: 6557
          - **Positive**: 877
          - **Prevalence**: 13.38%
      value: |
          - Observation type:
          - Total:
          - Positive:
          - Prevalence:
      render: markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Brief description of the data
      description: |
        A concise description of the data.

        Example:
        period: 2011-2015

        3969 patients admitted
        4582 blood culture episodes

        total, neg, none, pos
        total: 6557, 4319, 1361, 877
        train (70%): 4582, 3039, 940, 603
        val (20%): 1320, 852, 283, 185
        test (10%): 655, 428, 138, 89
        (see Table 1)

        none  = culture not drawn at all
    validations:
      required: false

  - type: textarea
    attributes:
      label: Brief description of the clinical variables
      description: |
        Example:
          33 features x 48 timesteps (t=1h) (appendix B)
          Demographics (1): Age
          Vital Signs (4): BT, DBP, HR, RR, HR_STD, RR_STD, CORR_HR_RR
          Laboratory (22): BUN, ALB, PLT, Chloride, Creatinine, Phosphorus, ALP, SO2, PCO2, SPO2, Glucose
          Other (x):

  - type: textarea
    attributes:
      label: Brief description of the pre-processing
      description: |
        A concise description of pre-processing (example)
        Outlier Removal
        Class Imbalance: RANDU, RANDO, SMOTE
        Inputation: M_MEDIAN, M_MEAN, FFILL, BFILL, M_MI, M_MASK
        Feature Engineering: FE_STATS, FE_DELTA, FE_DFT, FE_LR, FE_CATEGORY, FE_CRAFTED, FE_MASK
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Materials
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: Is the data publicly available?
        required: true
      - label: Is the code publicly available?
        required: true


  - type: textarea
    attributes:
      label: Feature ranking
      description: A concise description of models' performances
    validations:
      required: false

  - type: textarea
    attributes:
      label: Brief report of the target definition
      description: A concise description of models' performances
    validations:
      required: false

  - type: textarea
    attributes:
      label: Brief summary of interesting comments.
      description: A concise summary of interesting comments.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Brief summary of possible concerns.
      description: A concise summary of possible concerns.
    validations:
      required: false

  - type: textarea
    attributes:
      label: List of acronyms
      description: Please include any acronym used above.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Node**: 13.14.0
          - **npm**: 7.6.3
      value: |
          - OS:
          - Node:
          - npm:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: dropdown
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge