name: Manuscript
description: File a new manuscript
title: "[Manuscript] <title>"
labels: ["Bug", "Needs Triage"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true

- type: checkboxes
  attributes:
    label: Have you checked how the manuscripts are reported?
    description: Please have a look at the manuscript .xls file.
    options:
    - label: I have had a look the existing manuscripts.
      required: true

- type: textarea
  attributes:
    label: Link
    description: Link to the manuscript
  validations:
    required: false

- type: textarea
  attributes:
    label: Brief description
    description: A concise description of the manuscript
  validations:
    required: false

- type: textarea
  attributes:
    label: Metadata
    description: |
      Basic information of the manuscript (example):
        - **Year**: 2022
        - **Authors**: Boner et al
        - **Title**: Deep learning risk prediction...
        - **Tags**: FNN | CNN | GRU
        - **Score**: 7
    value: |
        - Year:
        - Authors:
        - Title:
        - Tags:
        - Score:
    render: markdown
  validations:
    required: false

- type: textarea
  attributes:
    label: Criteria
    description: |
      examples:
        - **Aim**: Prediction
        - **Ward**: ICU
        - **Dataset**: MIMIC | eICU
        - **Inclusion criteria**: Age>18, inpatient, underwent blood culture
        - **Positive**: BSI
    value: |
        - Aim:
        - Ward:
        - Dataset:
        - Inclusion criteria:
        - Positive:
    render: markdown
  validations:
    required: false

- type: textarea
  attributes:
    label: Data
    description: |
      examples:
        - **Observation type**: episodes
        - **Total**: 6557
        - **Positive**: 877
        - **Prevalence**: 13.38
    value: |
        - Observation type:
        - Total:
        - Positive:
        - Prevalence:
    render: markdown
  validations:
    required: false

- type: textarea
  attributes:
    label: Brief description of the data
    description: A concise description of the data
  validations:
    required: false

- type: textarea
  attributes:
    label: Clinical variables
    description: |
      examples:
        - **Total number of clinical variables**: 28
        - **Demographics**: 1
        - **Vital Signs**: 4
        - **Laboratory**: 22
        - **Other**: 1
    value: |
        - Total number of clinical variables:
        - Demographics
        - Vital signs
        - Laboratory
        - Other
    render: markdown
  validations:
    required: false

- type: textarea
  attributes:
    label: Brief description of the clinical variables
    description: |
      Example:
        33 features x 48 timesteps (t=1h) (appendix B)
        Demographics (1) -> Age
        Vital Signs (4)  -> BT, DBP, HR, RR, HR_STD, RR_STD, CORR_HR_RR
        Laboratory (22)  -> BUN, ALB, PLT, Chloride, Creatinine, Phosphorus, ALP, SO2, PCO2, SPO2, Glucose
        Other (x): 
    placeholder: |
      33 features x 48 timesteps (t=1h) (appendix B)
      Demographics (1) | Age
      Vital Signs (4) | BT, DBP, HR, RR, HR_STD, RR_STD, CORR_HR_RR
      Laboratory (22) | BUN, ALB, PLT, Chloride, Creatinine, Phosphorus,
        ALP, SO2, PCO2, SPO2, Glucose, Potassium, Sodium, ALT, Magnesium,
        Lactate, WBC, BIL, Troponin Test, Calcium

- type: textarea
  attributes:
    label: Brief description of the pre-processing
    description: A concise description of pre-processing
  validations:
    required: false

- type: textarea
  attributes:
    label: Brief report of the performance
    description: A concise description of models' performances
  validations:
    required: false

- type: checkboxes
  attributes:
    label: Materials
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: Is the data publicly available?
      required: true
    - label: Is the code publicly available?
      required: true


- type: textarea
  attributes:
    label: Feature ranking
    description: A concise description of models' performances
  validations:
    required: false

- type: textarea
  attributes:
    label: Brief report of the target definition
    description: A concise description of models' performances
  validations:
    required: false

- type: textarea
  attributes:
    label: Brief summary of interesting comments.
    description: A concise summary of interesting comments.
  validations:
    required: false

- type: textarea
  attributes:
    label: Brief summary of possible concerns.
    description: A concise summary of possible concerns.
  validations:
    required: false

- type: textarea
  attributes:
    label: List of acronyms
    description: Please include any acronym used above.
  validations:
    required: false

- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false