name: Manuscript
description: File a new manuscript
title: "[Manuscript] <title>"
labels: ["Bug", "Needs Triage"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true


- type: textarea
  attributes:
    label: Metadata
    description: |
      examples:
        - **Year**: 2022
        - **Authors**: Boner et al
        - **Title**: Deep learning risk prediction...
        - **Tags**: FNN | CNN | GRU
        - **Score**: 7
    value: |
        - Year:
        - Authors:
        - Title:
        - Tags:
        - Score:
    render: markdown
  validations:
    required: false

- type: textarea
  attributes:
    label: Criteria
    description: |
      examples:
        - **Aim**:
        - **Ward**: ICU
        - **Dataset**: MIMIC | eICU
        - **Inclusion criteria**: Age>18, inpatient, underwent blood culture
        - **Positive**: BSI
    value: |
        - Aim:
        - Ward:
        - Dataset:
        - Inclusion criteria:
        - Positive:
    render: markdown
  validations:
    required: false

- type: textarea
  attributes:
    label: Data
    description: |
      examples:
        - **Observation type**: episodes
        - **Total**: 6557
        - **Positive**: 877
        - **Prevalence**: 13.38
        - **Number of clinical variables**: 28
        - **Demographics**: 1
        - **Vital Signs**: 4
        - **Laboratory**: 22
        - **Other**: 1
    value: |
        - Observation type:
        - Total:
        - Positive:
        - Prevalence:
        - Number of clinical variables:
        - Demographics
        - Vital signs
        - Laboratory
        - Other
    render: markdown
  validations:
    required: false

- type: textarea
  attributes:
    label: Brief description
    description: A concise description of the manuscript
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false